### PR TITLE
I have solve the bug #2 Contact Us button Responsive

### PR DESCRIPTION
**Pull request by kunal-511**
I have made changes to styling to fix the Make Contact Us button Responsive for mobile

### CODE REVIEW

**Comment by kunal-511** [comment]
i have fix please merge to main branch

**Comment by kunal-511** [comment]
Please merge this under hacktober fest label

**Comment by karantec** [comment]
Sure

**Comment by kunal-511** [comment]
????

**Comment by kunal-511** [comment]
Please merge this under hacktober fest

**Pull request closed without merging**
